#!/bin/bash

curl -ss https://raw.githubusercontent.com/rubyonracetracks/docker-debian-stretch-build/master/jekyll-general/usr_local_bin/check-jekyll-general | bash

echo '###############################################'
echo 'BEGIN jekyll-rubyonracetracks-com sanity checks'
echo '###############################################'

echo 'No additional sanity checks'

echo '##################################################'
echo 'FINISHED jekyll-rubyonracetracks-com sanity checks'
echo '##################################################'
